name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: Bedrock-OSS/regolith-action@v1.1.0
        with:
          profile: build-release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: "*.mcaddon"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.mcaddon"
          generate_release_notes: true